version: '3.1'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME= username
      - MONGO_INITDB_ROOT_PASSWORD= password
  mongo-express:
    image: mongo-express
    ports:
      - 9090:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME= username
      - ME_CONFIG_MONGODB_ADMINPASSWORD= password
      - ME_CONFIG_MONGODB_SERVER= mongodb
    restart: unless-stopped 
